#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#aliases
alias em='emacsclient -c -a ""'

#suffix aliases
alias -s html=chromium
alias -s org=em

export PIC_GCC_HOME=/opt/microchip/xc16/v1.11
export PIC_APPLIB_HOME=/opt/microchip/applibs/v1.4.2

path+=$PIC_GCC_HOME/bin
